### PR TITLE
Made a simple script to run the tutorial notebooks

### PR DESCRIPTION
**Pull request by ejlilley**

### CODE REVIEW

**Comment by prashjet** [comment]
I ran this and got the output:

```
(dcdirect) prash@air > ./test_notebooks.sh 
Failed on notebook: 1_data_prep_for_gauss_hermite.ipynb

All notebooks ran successfully!
```

When I run the notebook `1_data_prep_for_gauss_hermite.ipynb` manually however, it works (at least as far as I can see). Things to look into:
1. why it said the first test failed?
2. why it said all notebooks ran successfully after it said the first test failed?
3. perhaps also write out success statements per notebook, rather than just failure?

**Comment by ejlilley** [comment]
Try now; I get the following output:
```
Passed on notebook: 1_data_prep_for_gauss_hermite.ipynb
Failed on notebook: 2_quickstart.ipynb
Passed on notebook: 3_model_iterations_and_plots.ipynb
Passed on notebook: 4_BayesLOSVD.ipynb
Passed on notebook: 5_parameter_space.ipynb
Passed on notebook: 6_orbits_and_weights.ipynb
```

**Comment by prashjet** [comment]
I now get...

```
(dcdirect) prash@air > ./test_notebooks.sh
Failed on notebook: 1_data_prep_for_gauss_hermite.ipynb
Passed on notebook: 2_quickstart.ipynb
Passed on notebook: 3_model_iterations_and_plots.ipynb
Passed on notebook: 4_BayesLOSVD.ipynb
Passed on notebook: 5_parameter_space.ipynb
Passed on notebook: 6_orbits_and_weights.ipynb
```

... but still not clear why notebook 1 fails. When I run it manually, it appears to work fine. Is there any extra output I can add to the script that could help explain...? Or something I could see directly in the notebook?

**Comment by maindlt** [comment]
Hi there,

thanks for the script, Edward!

I think the problem above was caused by `test_notebooks` being branched off a rather old DYANMITE 3.0 `master` branch which lacked many new features, also `1_data_prep_for_gauss_hermite.ipynb` was called `1_data_prep_for_gauss_hermites.ipynb`, etc.

After merging the current `master` branch into here, deleting previous installs (`rm -r ~/.local/lib/python3.9/site-packages/dynamite*` or similar), and re-installing DYNAMITE, the test script works for me:

```
$ ./test_notebooks.sh
Passed on notebook: 1_data_prep_for_gauss_hermite.ipynb
Passed on notebook: 2_quickstart.ipynb
Passed on notebook: 3_model_iterations_and_plots.ipynb
Passed on notebook: 4_BayesLOSVD.ipynb
Passed on notebook: 5_parameter_space.ipynb
Passed on notebook: 6_orbits_and_weights.ipynb
```

@prashjet: please test one last time to make sure it works, then we are ready to merge.

Cheers, Thomas

**Comment by prashjet** [comment]
Great - that solved it.

Thanks Thomas! Will merge :)

**Pull request merged**
