### PR TITLE
Analysis class

### PR DESCRIPTION
**Pull request by maindlt**
New `Analysis` class in new source file `analysis.py`. Its first method is `get_gh_model_kinematic_maps()` which calculates a model's flux and gh kinematics coefficients. it allows to plot kinematic maps more efficiently and for all (so far implemented) weight solvers.

### CODE REVIEW

**Comment by maindlt** [comment]
Hi @sthater and @azocchi,

as discussed today: here is a summary for testing `Analysis` with a larger orblib...

Many thanks for testing and cheers,
Thomas

- After solving with the legacy weight solver:
  - The best model directory should have a file `model_gh_kins_<kin set used>_fit.ecsv`.
  - The plots directory should have two figures `kinematic_map_<kin set used>old.png` and `kinematic_map_<kin set used>.png`.
    - `kinematic_map_<kin set used>old.png` uses the old plotting routine that reads the gh coefficients from legacy `nn_kinem.out` and only works with the legacy weight solver.
    - `kinematic_map_<kin set used>.png` uses the new `Analysis` functionality that determines the model's gh coefficients via `dyn.kinematics.GaussHermite.transform_orblib_to_observables()` applied to the weighted average of the model's orbits' losvds. It works for all implemented weight solvers.
  - Please verify that the two figures are (almost) identical. If they are it is an indication for correctly having implemented the `Analysis` class.
  - Save the kinematic map figures for comparing with NNLS-scipy weight solver results below.
- After solving with the NNLS-scipy weight solver:
  - As above, the best model directory should have a file `model_gh_kins_<kin set used>_fit.ecsv`.
  - The plots directory should have only one non-blank figure, `kinematic_map_<kin set used>.png`.
  - This figure is the kinematic map of the best model obtained via the NNLS-scipy weight solver and  should be (almost) identical to the figure of the same name obtained via the legacy weight solver. If it is, it is an indiction for a correct `Analysis` class and compatible results of the legacy and NNLS-scipy weight solvers.

If the tests are successful I'd recommend to delete the old plotting routines.

**Comment by azocchi** [comment]
Hi @maindlt, I tested this again with the corrected input data (see PR #291), and I do see some differences between the two figures, mainly in the central region for the velocity dispersion and h3 moment (visible in the residuals) and in the h4 moment (model + residuals). I will try to do some additional tests to see what is going on! 

Also, not sure if I am doing something wrong on my hand, but in the `kinchi2_vs_model_id.png` I see a discrepancy between the positions of crosses and circles. I will double check this!

**Comment by maindlt** [comment]
Hi @azocchi,

> Also, not sure if I am doing something wrong on my hand, but in the `kinchi2_vs_model_id.png` I see a discrepancy between the positions of crosses and circles. I will double check this!

With the corrected input data the positions of the circles also changed. For their correct positions please copy the following file from the branch with the corrected "h3=0" input data: `dev_tests/data/chi2_compare_ml_654.dat`

On the other topic (figures differ): many thanks for testing! I will have a look at it, too ;-)

Cheers, Thomas

**Comment by azocchi** [comment]
Thanks for the suggestion, the crosses are back within the circles! ;)

**Comment by maindlt** [comment]
Hi again @azocchi :-)

hm, strange - I can reproduce your deviations in the central region for the velocity dispersion and h3+h4 with the test galaxy. However, tests with FCC047 (both kinematic sets) resulted in indistinguishable figures between
`legacy NNLS+new get_gh_model_kinematic_maps()`, `legacy NNLS+old plotting routine`, `SciPy NNLS+new get_gh_model_kinematic_maps()`. Can it be connected to missing h3 and h4 data for the test galaxy...? Perhaps we can discuss this in our next meeting...

Cheers, Thomas

**Comment by maindlt** [comment]
Here are kinematic maps for a SAMI galaxy (small orbit library, `(nE, nI2, nI3, dithering) = (6, 5, 4, 3)`). The only noticeable difference is in the h4 residuals.
Top: Fortran NNLS, new kinmap plotting routine
Middle: Fortran NNLS, old kinmap plotting routine
Bottom: SciPy NNLS, new kinmap plotting routine

fortran_new
fortran_old
scipy_new

**Comment by maindlt** [comment]
Kinematic maps for the same SAMI galaxy (slightly different config file, significantly larger orblib `(nE, nI2, nI3, dithering) = (21, 10, 7, 3)`). Again, there are small differences in the h4 residuals (very small this time), probably connected to CRCut...?
Top: Fortran NNLS, new kinmap plotting routine
Bottom: Fortran NNLS, old kinmap plotting routine

2fortran_new
2fortran_old

**Comment by maindlt** [comment]
Can be merged per today's hack session...

**Comment by maindlt** [comment]
Merged master into this branch and removed the old kinematic map plotting method from plotter.py.
Tested with our test galaxy and FCC047, both tests were successful.
Will now merge and delete branch...

**Pull request merged**
