### PR TITLE
Kinmapchi2 for python nnls

### PR DESCRIPTION
**Pull request by maindlt**
Chi2 based on the kinematic maps (v, sigma, h3, h4,...), `kinmapchi2`, can now be calculated for the python NNLS (was available for the LegacyWeightSolver only).

For this, calculating `kinmapchi2` was completely re-implemented for all weight solvers in method `WeightSolver.chi2_kinmap(weights)`. Probably because v and sigma are determined via fitting a Gaussian to the respective histograms (just like in kinematic maps plotting), the `kinmapchi2` values are a bit different from the ones read from the LegacyWeightSolver output (about 2.7% based on `test_nnls.py` and runs with both weight solvers).

Also added a weights table output feature to the LegacyWeightSolver so that now all weight solvers write the same ecsv output.

If you have time, please test and comment on the acceptability of the 2.7% difference ;-)

### CODE REVIEW

**Comment by maindlt** [comment]
Comparison of `test_nnls.py` results:
Previous method (`kinmapchi2` values read & calulated from the `LegacyWeightSolver` output `nn_kinem.out`, only available for `LegacyWeightSolver`):
```
  m-bh    a-bh  c-dh  f-dh q-stars p-stars u-stars  ml        chi2             kinchi2           kinmapchi2         time_modified      orblib_done weights_done all_done which_iter        directory
-------- ----- ------ ---- ------- ------- ------- --- ------------------ ------------------ ----------------- ----------------------- ----------- ------------ -------- ---------- -----------------------
100000.0 0.001 1000.0 10.0    0.54    0.99  0.9999 5.0 161713.86235521018 125924.28211505871 983816.5357107143 2023-08-10T21:39:35.000        True         True     True          0 orblib_000_000/ml05.00/
100000.0 0.001 1000.0 10.0    0.54    0.99  0.9999 1.0 42418.835768625584   18223.0332977481 34721.57131534838 2023-08-10T21:39:35.000        True         True     True          1 orblib_000_000/ml01.00/
100000.0 0.001 1000.0 10.0    0.54    0.99  0.9999 9.0 137996.62182152033  106730.2202381026 2525562.934382647 2023-08-10T21:39:35.000        True         True     True          1 orblib_000_000/ml09.00/
```
New method (using `WeightSolver.chi2_kinmap(weights)`):
`LegacyWeightSolver`
```
  m-bh    a-bh  c-dh  f-dh q-stars p-stars u-stars  ml        chi2             kinchi2           kinmapchi2          time_modified      orblib_done weights_done all_done which_iter        directory
-------- ----- ------ ---- ------- ------- ------- --- ------------------ ------------------ ------------------ ----------------------- ----------- ------------ -------- ---------- -----------------------
100000.0 0.001 1000.0 10.0    0.54    0.99  0.9999 5.0 161713.86235521018 125924.28211505871 1005436.8699955629 2023-08-10T21:32:41.000        True         True     True          0 orblib_000_000/ml05.00/
100000.0 0.001 1000.0 10.0    0.54    0.99  0.9999 1.0 42418.835768625584   18223.0332977481  36040.63890041469 2023-08-10T21:32:41.000        True         True     True          1 orblib_000_000/ml01.00/
100000.0 0.001 1000.0 10.0    0.54    0.99  0.9999 9.0 137996.62182152033  106730.2202381026 2581953.2688042363 2023-08-10T21:32:41.000        True         True     True          1 orblib_000_000/ml09.00/
```
scipy `NNLS`
```
  m-bh    a-bh  c-dh  f-dh q-stars p-stars u-stars  ml        chi2             kinchi2           kinmapchi2          time_modified      orblib_done weights_done all_done which_iter        directory
-------- ----- ------ ---- ------- ------- ------- --- ------------------ ------------------ ------------------ ----------------------- ----------- ------------ -------- ---------- -----------------------
100000.0 0.001 1000.0 10.0    0.54    0.99  0.9999 5.0  163279.3585301296  127321.6757531478 1000011.3059815513 2023-08-10T21:34:16.000        True         True     True          0 orblib_000_000/ml05.00/
100000.0 0.001 1000.0 10.0    0.54    0.99  0.9999 1.0  42453.69372127462  18223.81866655845  35912.95977085516 2023-08-10T21:34:16.000        True         True     True          1 orblib_000_000/ml01.00/
100000.0 0.001 1000.0 10.0    0.54    0.99  0.9999 9.0 139190.47990540892 108164.22591994907  2602700.254474954 2023-08-10T21:34:16.000        True         True     True          1 orblib_000_000/ml09.00/
```

**Comment by maindlt** [comment]
Hi @prashjet and @sthater,

as discussed today, it would be great could you test this PR with a 'non-trivial' galaxy (>1 non-fixed parameter, etc.).

Sabine: please use config file setting
```
weight_solver_settings:
    type: "LegacyWeightSolver"
    nnls_solver: 1
```

Prash: please use config file setting
```
weight_solver_settings:
    type: "NNLS"
    nnls_solver: 'scipy'
```
Testing procedure:
1. Run a few iterations, inspect the `kinmapchi2` values in the all_models table.
2. Add one or more iterations with a second DYNAMITE run and verify that this works.
3. Inspect the all_models table and save it somewhere else.
4. Run the same iterations with the code from the master branch and verify that the `kinmapchi2`-values are close.

Many thanks and cheers,
Thomas

**Comment by maindlt** [comment]
Hi @sthater and @prashjet,

I could not let go - the last commit should make it possible to continue old runs with the `LegacyWeightSolver`, only 4 more lines of code... The method should be fully compatible with the `Model.get_weights()` method (used by the Analysis and Plotter classes) because it calls the `WeightSolver.solve()` method which in turn reads existing data and if the weights file is not existing, it will create it upon the first call.

The only limitation is that old `LegacyWeightSolver` runs cannot be continued with the scipy NNLS. Workaround: calling `Model.get_weights()` on all existing models to create the weights files, but that's probably stretching it...

Let me know what you think, perhaps we won't need to rush releasing two releases after all...

Cheers,
Thomas

**Comment by prashjet** [comment]
I more or less did the following:

> Testing procedure:
> 
> 1. Run a few iterations, inspect the kinmapchi2 values in the all_models table.
> 2. Add one or more iterations with a second DYNAMITE run and verify that this works.
> 3. Inspect the all_models table and save it somewhere else.
> 4. Run the same iterations with the code from the master branch and verify that the kinmapchi2-values are close.

Setup: 2 free params (`ml` & `f_dm`). Start with 4 models produced by `FullGrid` then switching to `LegacyGridSearch` to add 4 more models. In all cases below, identical parameter lists are generated.

Here are the resulting `kinmapchi2` values. Using `LegacyWeightSolver`:

```
    kinmapchi2    
------------------
 74980.33136167636
 49772.92890019686
 54768.18645254749
 153999.5255887669
58798.604915884694
 81266.34115377656
 42504.44156228304
 23857.45130716322
```

with `NNLS`:

```
    kinmapchi2    
------------------
 73427.31437091822
 49831.96099365194
 54548.93128352338
 152217.7567160483
 58500.33809891473
 80118.76168753469
41965.936167707805
 23879.67772101332
```

I'm satisfied that these are a close enough match.

Everything above was run from the `kinmapchi2_for_python_nnls` branch. Re-running from branch `master` as suggested, with `LegacyWeightSolver` gives the following:

```
    kinmapchi2    
------------------
 74999.38826898485
49766.507882430786
54753.495638351655
180208.76262994218
 58800.72603149484
 99728.29449456796
 42481.00604266759
23851.807296894774
```

which is largely similar except for the third row from the bottom. Re-running again from `master` but with a different random seed gives

```
    kinmapchi2    
------------------
 76491.51881890604
 49704.88693633562
54904.454892487054
180843.72283326794
 58880.00862570841
100864.12901310157
 43496.23295194898
24026.798580051007
```

which again is similar except for the third row from the bottom. So this model has a larger natural stochasticity.

I think safe to conclude the two weight solvers give consistent values of `kinmapchi2`.

**Pull request merged**
