### PR TITLE
Fortran fix

### LINKED ISSUE #162: "test_orbit_losvds.py" is not working
The test "test_orbit_losvdx.py" is not working even if the installation of dynamite has been completed without errors.

The error is the following:
test_error

After a little bit of investigation we found that the error was related to the subroutine "integrator_integrate" in the "orblib_f.f90" module. More precisely, it seems that the variable alldone, which to my comprehension should be true only after having integrated all the orbits, became true just after the first iteration. 
 Changing the definitions of the variables done, alldone from intent(out) to intent(inout) has worked for us.

This error has been found at least on ubuntu 20.04 with gfortran 9.3.

### PR DESCRIPTION
**Pull request by azocchi**
After updating DYNAMITE to version 3, while running ```dev_tests/test_nnls.py``` I got the error that you can see at the bottom of this message. I took a closer look at this error, and I think that I found a way to solve it. Please check it out to see if it works also on other operating systems. I tested it on Ubuntu 22.04 and Fedora 36, and it seems to be working (even though for Fedora I have some other issues, see below). I tested this only by running ```dev_tests/test_nnls.py``` for the moment, but I will try to run some more tests with the other tutorial notebooks.

On Fedora however I have the problem that the computation hangs indefinitely at some point: the code gets past the point where I was getting the error before, but it hangs without arriving at the end. I seem to remember that this is a problem that came up at some point for someone else, but I forgot (and cannot find here) what the solution was: any idea?
By comparing the log file with the one from Ubuntu, which gets to the end of the calculation, it seems that on Fedora my run stops before spitting out this line in the log file:
```[DEBUG] Jul 25 12:15:35 - dynamite.physical_system.System - physical_system.py:get_component_from_class:162 - Checking for 1 and only 1 component of class <class 'dynamite.physical_system.TriaxialVisibleComponent'>...```

Actually, while looking for a clue on how to solve the hanging issue, I took a look at the open issues and saw that @FabioRigamonti had already found a solution for the Fortran problem when running one of the test files. My implementation is different from the one he proposes, but has the same effect (I think!). Closes #162.

-------------------------------

```
[ERROR] 16:00:39 - dynamite.weight_solvers.LegacyWeightSolver - cmd_nnls_5.0 exit code 1. ERROR. Message: At line 168 of file triaxnnls_CRcut.f90 (unit = 27, file = 'datfil/orblib_5.0.dat')
Fortran runtime error: I/O past end of record on unformatted file

Error termination. Backtrace:
#0  0x57756a in ???
#1  0x5777c7 in ???
#2  0x5782bf in ???
#3  0x582ad9 in ???
#4  0x43d3c0 in ???
#5  0x44033c in ???
#6  0x40279c in ???
#7  0x7faaed42954f in ???
#8  0x7faaed429608 in ???
#9  0x402864 in ???
#10  0xffffffffffffffff in ???
Logfile: NGC6278_output/models/orblib_000_000/ml5.00/nnls.log
multiprocess.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/multiprocess-0.70.13-py3.10.egg/multiprocess/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.10/site-packages/multiprocess-0.70.13-py3.10.egg/multiprocess/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/usr/local/lib/python3.10/site-packages/dynamite-3.0.0-py3.10.egg/dynamite/model_iterator.py", line 376, in create_and_run_model
    weight_solver = mod.get_weights(orblib)
  File "/usr/local/lib/python3.10/site-packages/dynamite-3.0.0-py3.10.egg/dynamite/model.py", line 666, in get_weights
    weights, chi2_tot, chi2_kin = weight_solver.solve(orblib)
  File "/usr/local/lib/python3.10/site-packages/dynamite-3.0.0-py3.10.egg/dynamite/weight_solvers.py", line 230, in solve
    raise RuntimeError(text)
RuntimeError: cmd_nnls_5.0 exit code 1. ERROR. Message: At line 168 of file triaxnnls_CRcut.f90 (unit = 27, file = 'datfil/orblib_5.0.dat')
Fortran runtime error: I/O past end of record on unformatted file

Error termination. Backtrace:
#0  0x57756a in ???
#1  0x5777c7 in ???
#2  0x5782bf in ???
#3  0x582ad9 in ???
#4  0x43d3c0 in ???
#5  0x44033c in ???
#6  0x40279c in ???
#7  0x7faaed42954f in ???
#8  0x7faaed429608 in ???
#9  0x402864 in ???
#10  0xffffffffffffffff in ???
Logfile: NGC6278_output/models/orblib_000_000/ml5.00/nnls.log
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/alice/dynamite/dev_tests/test_nnls.py", line 141, in <module>
    run_user_test()
  File "/home/alice/dynamite/dev_tests/test_nnls.py", line 62, in run_user_test
    smi = dyn.model_iterator.ModelIterator(c)
  File "/usr/local/lib/python3.10/site-packages/dynamite-3.0.0-py3.10.egg/dynamite/model_iterator.py", line 86, in __init__
    status = model_inner_iterator.run_iteration()
  File "/usr/local/lib/python3.10/site-packages/dynamite-3.0.0-py3.10.egg/dynamite/model_iterator.py", line 515, in run_iteration
    output = p.map(self.create_and_run_model, input_list)
  File "/usr/local/lib/python3.10/site-packages/multiprocess-0.70.13-py3.10.egg/multiprocess/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/local/lib/python3.10/site-packages/multiprocess-0.70.13-py3.10.egg/multiprocess/pool.py", line 771, in get
    raise self._value
RuntimeError: cmd_nnls_5.0 exit code 1. ERROR. Message: At line 168 of file triaxnnls_CRcut.f90 (unit = 27, file = 'datfil/orblib_5.0.dat')
Fortran runtime error: I/O past end of record on unformatted file

Error termination. Backtrace:
#0  0x57756a in ???
#1  0x5777c7 in ???
#2  0x5782bf in ???
#3  0x582ad9 in ???
#4  0x43d3c0 in ???
#5  0x44033c in ???
#6  0x40279c in ???
#7  0x7faaed42954f in ???
#8  0x7faaed429608 in ???
#9  0x402864 in ???
#10  0xffffffffffffffff in ???
Logfile: NGC6278_output/models/orblib_000_000/ml5.00/nnls.log
```

### CODE REVIEW

**Comment by ejlilley** [comment]
This works for me, running GCC/gfortran 9.4.0 under Arch Linux. I tried both test_nnls.py and a longer run (~50 models) on an Atlas3D galaxy.

**Comment by maindlt** [comment]
Tested on Mac OS 11.6.7 Big Sur and gcc/gfortran 10.3.0: `test_nnls.py` and `test_all.sh` both work ok :-)

**Comment by azocchi** [comment]
I also did some further checks: the tutorial notebooks (in ```docs/tutorial_notebooks```) all work fine on Ubuntu (some problems on Fedora for number 3 and 4, but not related to the orbit calculation, which is totally fine there as well!). Moreover, ```test_orbit_losvds.py``` works nicely on both Ubuntu and Fedora! :)

**Comment by ejlilley** [comment]
Also works with GCC 12.1.0 under Arch Linux (after I removed the static-libs compiler flags in Makefile.linux, which I think are unnecessary)

**Comment by maindlt** [comment]
> Also works with GCC 12.1.0 under Arch Linux (after I removed the static-libs compiler flags in Makefile.linux, which I think are unnecessary)

Interestingly, the same is the case for Mac OS 11.6.7 / gcc 10.3.0: commenting out the static-libs compiler flags in Makefile compiles successfully and `test_nnls.py`, `test_orbit_losvds.py`, and `test_all.sh` execute successfully. Perhaps we can delete the static-libs part from both Makefiles?

**Pull request merged**
