### PR TITLE
Fix freezing weight solver

### PR DESCRIPTION
**Pull request by maindlt**
Users experienced problems (freezing and/or crashes) in weight solving. Strangely, some issues only occurred in batch jobs and notebooks, but not in directly executed Python scripts (same Python version, same package versions, same environment).

Two problems were identified, individual numpy and scipy versions seem to behave differently depending on 'interactive' or 'batch' use (?). In 'batch' use (i.e., notebooks and probably slurm jobs): (a) `numpy.einsum(..., optimize=True)` freezes without an error message in newer numpy versions and (b) `scipy.optimize.nnls` freezes without an error message in scipy >= 1.12.

This PR fixes this behavior by
- Replacing `optimize=True` by `optimize=False` in `numpy.einsum`, avoiding einsum freezes in newer numpy versions (reason unclear).
- Putting more stringent constraints on the `numpy` and `scipy` releases, based on (a) [this](https://docs.scipy.org/doc/scipy-1.14.1/dev/toolchain.html) information on scipy.org and (b) DYNAMITE tests (execution from command line and notebooks/shell scripts) which further narrowed down working numpy-scipy releases. Educated guess: it may be connected to the reimplementation of `scipy.optimize.nnls` in `scipy 1.12` as mentioned in #401.
- Updating the supported Python versions in the docs, eliminating Python 3.8 as it reached its end of life last October.

With these changes, weight solving should not freeze anymore.

Tested so far:
- `test_nnls.py` works as expected with all three weight solvers (NNLS/scipy, NNLS/cvxopt, LegacyWeightSolver)
- `test_notebooks.sh` executes all tutorial notebooks successfully (did freeze previously)
- The previously freezing `2_quickstart.ipynb` works as expected

@prashjet, if you have time:
While the tests were executed in a fresh Python 3.11 environment, it would be great if you can test on your machine as well (`test_nnls.py` and the tutorial notebooks via `test_notebooks.sh` and interactively).

@afeldmei:
I think this PR might solve your issue with the slurm jobs that freeze forever but (at least partly) execute when started interactively. Please try to check out this PR (or apply its changes manually) and resubmit a job to verify.

### CODE REVIEW

**Comment by boeckera** [comment]
Hi,Maybe what could be an issue that came to mymind regarding running this a cluster, where you are presumably running Dynamite in like an ‚embarrassingly‘ parallel way. In case this isn’t done, the environment variable OMP_NUM_THREADS should be set to one, because as default numpy will parallelize certain tasks under the hood and will take however many cpus are available. However, if you run this on a computing node and you allocate all the cpus for Dynamite it could be that the node gets overbooked and it starts to freeze. Just a thought that came to my mind while reading this.Cheers,AlinaAm 30.11.2024 um 11:55 schrieb Thomas I. Maindl ***@***.***>:﻿Users experienced problems (freezing and/or crashes) in weight solving. Strangely, some issues only occurred in batch jobs and notebooks, but not in directly executed Python scripts (same Python version, same package versions, same environment).
Two problems were identified, individual numpy and scipy versions seem to behave differently depending on 'interactive' or 'batch' use (?). In 'batch' use (i.e., notebooks and probably slurm jobs): (a) numpy.einsum(..., optimize=True) freezes without an error message in newer numpy versions and (b) scipy.optimize.nnls freezes without an error message in scipy >= 1.12.
This PR fixes this behavior by

Replacing optimize=True by optimize=False in numpy.einsum, avoiding einsum freezes in newer numpy versions (reason unclear).
Putting more stringent constraints on the numpy and scipy releases, based on (a) this information on scipy.org and (b) DYNAMITE tests (execution from command line and notebooks/shell scripts) which further narrowed down working numpy-scipy releases. Educated guess: it may be connected to the reimplementation of scipy.optimize.nnls in scipy 1.12 as mentioned in #401.
Updating the supported Python versions in the docs, eliminating Python 3.8 as it reached its end of life last October.

With these changes, weight solving should not freeze anymore.
Tested so far:

test_nnls.py works as expected with all three weight solvers (NNLS/scipy, NNLS/cvxopt, LegacyWeightSolver)
test_notebooks.sh executes all tutorial notebooks successfully (did freeze previously)
The previously freezing 2_quickstart.ipynb works as expected

@prashjet, if you have time:
While the tests were executed in a fresh Python 3.11 environment, it would be great if you can test on your machine as well (test_nnls.py and the tutorial notebooks via test_notebooks.sh and interactively).
@afeldmei:
I think this PR might solve your issue with the slurm jobs that freeze forever but (at least partly) execute when started interactively. Please try to check out this PR (or apply its changes manually) and resubmit a job to verify.



You can view, comment on, or merge this pull request online at:
  https://github.com/dynamics-of-stellar-systems/dynamite/pull/423

Commit Summary

  ddd4f67  Updated numpy and scipy requirements to avoid NNLS weight solver freeze.
  bc5ac80  Docs and changelog update: exclude Python 3.8 (end of life reached), added Python 3.11 to tested versions.


File Changes  (4 files)

  
    M
    docs/getting_started/installation.rst
    (6)
  
  
    M
    docs/more_info/changelog.rst
    (1)
  
  
    M
    dynamite/kinematics.py
    (8)
  
  
    M
    requirements.txt
    (4)
  


Patch Links:

  https://github.com/dynamics-of-stellar-systems/dynamite/pull/423.patch
  https://github.com/dynamics-of-stellar-systems/dynamite/pull/423.diff

**Comment by maindlt** [comment]
Hi @boeckera,

this is a very good point! If I remember correctly, we had in mind that most users will choose the `LegacyGridSearch` parameter generator which would typically come up with fewer new models than there are cores on a many-core cluster node. But then we introduced the `orblibs_in_parallel` configuration setting which doubles the cores used per model... Also, some users use the `FullGrid` parameter generator which easily produces hundreds of models saturating the available cpu cores, in addition to the parallel orblibs and multiple threads in numpy/scipy...
Hence, the last commit
- extends the documentation on multiprocessing, clarifying the interdependence of the parameters `ncpus`, `ncpus_weights`, `orblibs_in_parallel`, and the environment variable `OMP_NUM_THREADS` and
- changes the `orblibs_in_parallel`  default to `False` (for compatibility with the `ncpus=ncpus_weights='all_available'` defaults).
If desired, we can of course also discuss more sensible defaults depending on the `MAX_THREADS` in the numpy/scipy configuration and the individual machine's hardware, but that's probably an overkill...?

Cheers,
Thomas

**Comment by afeldmei** [comment]
I tested the branch on VSC-4, and downgraded my scipy to v1.11. The suggested tests pass. My weight-solving issues have been solved, all open weights are now solved.

**Comment by maindlt** [comment]
Great, many thanks for testing, @afeldmei! Will Squash and merge & delete branch...

**Pull request merged**
