### PR TITLE
Coloring prep: population data can have arbitrary column names

### PR DESCRIPTION
**Pull request by maindlt**
Tested with test_nnls.py and all combinations of `kinematics:` - `with_pops: True/False` and existing/non-existing `populations:` section in the configuration file.

BayesLOSVD: it should also work with pops data in the kinematics file. Open question: which binID is relevant, `bin_ID_BayesLOSVD` or `binID_dynamite`? Currently the code assumes `binID_dynamite`.

Input is most welcome ;-)

### CODE REVIEW

**Comment by prashjet** [comment]
When population data is in a separate file, everything works as expected.

When population data is in the kinematics file, then if the extra columns are not [t, dt, Z, dZ], I run into the error below.

```
KeyError                                  Traceback (most recent call last)
Cell In[14], [line 2](vscode-notebook-cell:?execution_count=14&line=2)
      [1](vscode-notebook-cell:?execution_count=14&line=1) fname = 'user_test_config_ml.yaml'
----> [2](vscode-notebook-cell:?execution_count=14&line=2) c = dyn.config_reader.Configuration(fname)
      [3](vscode-notebook-cell:?execution_count=14&line=3) mod = c.all_models.get_model_from_row(0)
      [4](vscode-notebook-cell:?execution_count=14&line=4) orblib = mod.get_orblib()

File /opt/miniconda3/envs/dyn_new_install_test/lib/python3.12/site-packages/dynamite/config_reader.py:285, in Configuration.__init__(self, filename, reset_logging, user_logfile, reset_existing_output)
    [283](https://file+.vscode-resource.vscode-cdn.net/opt/miniconda3/envs/dyn_new_install_test/lib/python3.12/site-packages/dynamite/config_reader.py:283) for kin, data_kin in data_comp['kinematics'].items():
    [284](https://file+.vscode-resource.vscode-cdn.net/opt/miniconda3/envs/dyn_new_install_test/lib/python3.12/site-packages/dynamite/config_reader.py:284)     path=self.settings.io_settings['input_directory']
--> [285](https://file+.vscode-resource.vscode-cdn.net/opt/miniconda3/envs/dyn_new_install_test/lib/python3.12/site-packages/dynamite/config_reader.py:285)     kinematics_set = getattr(kinem,data_kin['type'])\
    [286](https://file+.vscode-resource.vscode-cdn.net/opt/miniconda3/envs/dyn_new_install_test/lib/python3.12/site-packages/dynamite/config_reader.py:286)                         (name=kin,
    [287](https://file+.vscode-resource.vscode-cdn.net/opt/miniconda3/envs/dyn_new_install_test/lib/python3.12/site-packages/dynamite/config_reader.py:287)                          input_directory=path,
    [288](https://file+.vscode-resource.vscode-cdn.net/opt/miniconda3/envs/dyn_new_install_test/lib/python3.12/site-packages/dynamite/config_reader.py:288)                          **data_kin)
    [289](https://file+.vscode-resource.vscode-cdn.net/opt/miniconda3/envs/dyn_new_install_test/lib/python3.12/site-packages/dynamite/config_reader.py:289)     if kinematics_set.with_pops:
    [290](https://file+.vscode-resource.vscode-cdn.net/opt/miniconda3/envs/dyn_new_install_test/lib/python3.12/site-packages/dynamite/config_reader.py:290)         populations_set = popul.Populations(
    [291](https://file+.vscode-resource.vscode-cdn.net/opt/miniconda3/envs/dyn_new_install_test/lib/python3.12/site-packages/dynamite/config_reader.py:291)                 name=f'{kin}_pop',
    [292](https://file+.vscode-resource.vscode-cdn.net/opt/miniconda3/envs/dyn_new_install_test/lib/python3.12/site-packages/dynamite/config_reader.py:292)                 input_directory=path,
   (...)
    [300](https://file+.vscode-resource.vscode-cdn.net/opt/miniconda3/envs/dyn_new_install_test/lib/python3.12/site-packages/dynamite/config_reader.py:300)                 kin_aper=kin_id,
    [301](https://file+.vscode-resource.vscode-cdn.net/opt/miniconda3/envs/dyn_new_install_test/lib/python3.12/site-packages/dynamite/config_reader.py:301)                 pop_cols=kinematics_set.pop_cols)

File /opt/miniconda3/envs/dyn_new_install_test/lib/python3.12/site-packages/dynamite/kinematics.py:190, in GaussHermite.__init__(self, **kwargs)
    [187](https://file+.vscode-resource.vscode-cdn.net/opt/miniconda3/envs/dyn_new_install_test/lib/python3.12/site-packages/dynamite/kinematics.py:187) def __init__(self, **kwargs):
    [188](https://file+.vscode-resource.vscode-cdn.net/opt/miniconda3/envs/dyn_new_install_test/lib/python3.12/site-packages/dynamite/kinematics.py:188)     # super goes left to right, i.e. first calls "Kinematics" __init__, then
    [189](https://file+.vscode-resource.vscode-cdn.net/opt/miniconda3/envs/dyn_new_install_test/lib/python3.12/site-packages/dynamite/kinematics.py:189)     # calls data.Integrated's __init__
--> [190](https://file+.vscode-resource.vscode-cdn.net/opt/miniconda3/envs/dyn_new_install_test/lib/python3.12/site-packages/dynamite/kinematics.py:190)     super().__init__(**kwargs)
    [191](https://file+.vscode-resource.vscode-cdn.net/opt/miniconda3/envs/dyn_new_install_test/lib/python3.12/site-packages/dynamite/kinematics.py:191)     self.logger = logging.getLogger(f'{__name__}.{__class__.__name__}')
    [192](https://file+.vscode-resource.vscode-cdn.net/opt/miniconda3/envs/dyn_new_install_test/lib/python3.12/site-packages/dynamite/kinematics.py:192)     if hasattr(self, 'data'):

File /opt/miniconda3/envs/dyn_new_install_test/lib/python3.12/site-packages/dynamite/kinematics.py:28, in Kinematics.__init__(self, weight, type, hist_width, hist_center, hist_bins, with_pops, **kwargs)
     [19](https://file+.vscode-resource.vscode-cdn.net/opt/miniconda3/envs/dyn_new_install_test/lib/python3.12/site-packages/dynamite/kinematics.py:19) def __init__(self,
     [20](https://file+.vscode-resource.vscode-cdn.net/opt/miniconda3/envs/dyn_new_install_test/lib/python3.12/site-packages/dynamite/kinematics.py:20)              weight=None,
     [21](https://file+.vscode-resource.vscode-cdn.net/opt/miniconda3/envs/dyn_new_install_test/lib/python3.12/site-packages/dynamite/kinematics.py:21)              type=None,
   (...)
     [26](https://file+.vscode-resource.vscode-cdn.net/opt/miniconda3/envs/dyn_new_install_test/lib/python3.12/site-packages/dynamite/kinematics.py:26)              **kwargs
     [27](https://file+.vscode-resource.vscode-cdn.net/opt/miniconda3/envs/dyn_new_install_test/lib/python3.12/site-packages/dynamite/kinematics.py:27)              ):
---> [28](https://file+.vscode-resource.vscode-cdn.net/opt/miniconda3/envs/dyn_new_install_test/lib/python3.12/site-packages/dynamite/kinematics.py:28)     super().__init__(**kwargs)
     [29](https://file+.vscode-resource.vscode-cdn.net/opt/miniconda3/envs/dyn_new_install_test/lib/python3.12/site-packages/dynamite/kinematics.py:29)     self.logger = logging.getLogger(f'{__name__}.{__class__.__name__}')
     [30](https://file+.vscode-resource.vscode-cdn.net/opt/miniconda3/envs/dyn_new_install_test/lib/python3.12/site-packages/dynamite/kinematics.py:30)     if hasattr(self, 'data'):

File /opt/miniconda3/envs/dyn_new_install_test/lib/python3.12/site-packages/dynamite/data.py:77, in Integrated.__init__(self, aperturefile, binfile, **kwargs)
     [75](https://file+.vscode-resource.vscode-cdn.net/opt/miniconda3/envs/dyn_new_install_test/lib/python3.12/site-packages/dynamite/data.py:75) self.logger = logging.getLogger(f'{__name__}.{__class__.__name__}')
     [76](https://file+.vscode-resource.vscode-cdn.net/opt/miniconda3/envs/dyn_new_install_test/lib/python3.12/site-packages/dynamite/data.py:76) if hasattr(self, 'data'):
---> [77](https://file+.vscode-resource.vscode-cdn.net/opt/miniconda3/envs/dyn_new_install_test/lib/python3.12/site-packages/dynamite/data.py:77)     self.PSF = self.data.meta['PSF']
     [78](https://file+.vscode-resource.vscode-cdn.net/opt/miniconda3/envs/dyn_new_install_test/lib/python3.12/site-packages/dynamite/data.py:78)     if abs(sum(self.PSF['weight'])-1.0) > 1e-8:
     [79](https://file+.vscode-resource.vscode-cdn.net/opt/miniconda3/envs/dyn_new_install_test/lib/python3.12/site-packages/dynamite/data.py:79)         txt = f"PSF weights add up to {sum(self.PSF['weight'])}, " + \
     [80](https://file+.vscode-resource.vscode-cdn.net/opt/miniconda3/envs/dyn_new_install_test/lib/python3.12/site-packages/dynamite/data.py:80)               "not 1.0."

KeyError: 'PSF'
```

**Comment by maindlt** [comment]
Hm, strange... I tried with the attached gauss_hermite_kins_with_pops*.yaml files (pops columns  [t, dt, Z, dZ], [age, dage, met, dmet], and [age, dage, met, dmet, index3, dindex3], resp.) and all three work ok with python 3.10 and 3.12... Can it be an issue with the ecsv format (I once had trouble with 'manually' generated ecsv files)?

**Comment by prashjet** [comment]
Apolgies Thomas - that was my mistake... I was not using the installation I thought I was using

**Review by prashjet — APPROVED** [review]
Tested successfully!

**Comment by maindlt** [comment]
> Apolgies Thomas - that was my mistake... I was not using the installation I thought I was using

All good, happens to me all the time 😂
Thanks for testing and approving, Prash! Will merge later tonight...

**Pull request merged**
